
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
	
  public static final int ELSE = 17;
  public static final int IDENT = 15;
  public static final int PLUS = 11;
  public static final int MINUS= 18;
  public static final int RBRACE = 4;
  public static final int RPARENT = 7;
  public static final int EQUAL = 12;
  public static final int SEMI = 5;
  public static final int RETURN = 10;
  public static final int IF = 16;
  public static final int LPARENT = 6;
  public static final int LBRACE = 3;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int NUM_CONST = 14;
  public static final int PROG = 2;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int VOID = 13;
  
  public static final int FOR = 19;
  public static final int NEW = 20;
  public static final int DO = 21;
  public static final int WHILE = 22;
  public static final int EXTENDS = 23;
  public static final int CONTINUE = 24;
  public static final int BREAK = 25;
  public static final int CLASS = 26;
  public static final int INTERFACE = 27;
  
  public static final int IS_EQ = 28;
  public static final int DIV = 29;
  public static final int IS_NOT_EQ = 30;
  public static final int CONST = 31;
  public static final int AND = 32;
  public static final int LESSER = 33;
  public static final int LBRACKET = 34;
  public static final int LESSER_OR_EQ = 35;
  public static final int MOD = 36;
  public static final int READ = 37;
  public static final int INC = 38;
  public static final int LARGER_OR_EQ = 39;
  public static final int RBRACKET = 40;
  public static final int CHAR_CONST = 41;
  public static final int OR = 42;
  public static final int BOOL_CONST = 43;
  public static final int LARGER = 44;
  public static final int DEC = 45;
  public static final int MUL = 46;
  public static final int ENUM = 47;
  public static final int DOT = 48;
  public static final int EQUALS = 49;
  

  


  
  


  
  
  
}

