
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 12 14:51:12 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 12;
  public static final int READ = 7;
  public static final int IDENT = 27;
  public static final int PLUS = 8;
  public static final int RBRACE = 23;
  public static final int RPARENT = 19;
  public static final int EQUAL = 13;
  public static final int SEMI = 16;
  public static final int RETURN = 26;
  public static final int NUM_CONST = 28;
  public static final int BOOL_CONST = 30;
  public static final int LBRACE = 22;
  public static final int LBRACKET = 21;
  public static final int RBRACKET = 20;
  public static final int INC = 14;
  public static final int LPARENT = 18;
  public static final int COMMA = 17;
  public static final int EOF = 0;
  public static final int DIV = 11;
  public static final int PROG = 2;
  public static final int DEC = 15;
  public static final int MINUS = 9;
  public static final int DOT = 25;
  public static final int ENUM = 24;
  public static final int CONST = 5;
  public static final int PRINT = 3;
  public static final int error = 1;
  public static final int NEW = 6;
  public static final int MUL = 10;
  public static final int VOID = 4;
  public static final int CHAR_CONST = 29;
}

